server:
  port: 443
  ssl:
    enabled: true
    protocol: TLSv1.2
    key-store: tls.p12
    key-store-password: password
    key-store-type: PKCS12
spring:
  main:
    banner-mode: "off"
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB